// GENERATED by nice-generate-exports — do not edit by hand
// To update: edit package.exports.json and run `npm run generate-exports`

/** Flexible icon component with 30+ built-in icons and custom SVG support. */

export { default } from "./components/Icon"
export * from "./components/Icon"
export * from "./components/Illustration"
export { getIconToken } from "./tokens"
export { iconNames } from "./constants"
export { registerVendorResolver } from "./services"
